/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcb97a2f1ef4518a5382d3c
*
* You will get 10% discount for each one of your friends
* 
*/
package com.todo.db.todo_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE TodoBase PLEASE EDIT ../Todo.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Todo object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.todo.db.todo_db.entity.Todo;

public class TodoBase implements RowMapper<Todo>{
	
	private Long _id;
	
	// Attributes
    private String details;
    private Integer status;
    private String title;
	
	
	// Relations m:m category
	private ArrayList<Long> category;
	
	// Relations m:m tags
	private ArrayList<Long> tags;
	
	
	@Override
	public Todo mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Todo obj = new Todo();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setDetails(rs.getString("details"));
			obj.setStatus(rs.getInt("status"));
			obj.setTitle(rs.getString("title"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getDetails() {
		return details;
	}


	public void setDetails(String details) {
		this.details = details;
	}
	public Integer getStatus() {
		return status;
	}


	public void setStatus(Integer status) {
		this.status = status;
	}
	public String getTitle() {
		return title;
	}


	public void setTitle(String title) {
		this.title = title;
	}
	
    
    
    
    
    // Relations m:m category
	public ArrayList<Long> getCategory() {
		return category;
	}

	public void setCategory(ArrayList<Long> category) {
		this.category = category;
	}
	
	
	public static class Todo_category implements RowMapper<Todo_category>{
		
		private Long _id;
		
		// Relations
	
		private Long id_Todo;
		private Long id_Category;
				
		@Override
		public Todo_category mapRow(ResultSet rs, int rowNum) throws SQLException {
			
			Todo_category obj = new Todo_category();
			try {
				obj.set_id(rs.getLong("id"));
				obj.setId_Todo(rs.getLong("id_Todo"));
				obj.setId_Category(rs.getLong("id_Category"));
			}
			catch(Exception e) {
				e.printStackTrace();
			}
			return obj;
		}
		public Long get_id() {
			return _id;
		}
	
		public void set_id(Long _id) {
			this._id = _id;
		}
	
		public Long getId_Todo() {
			return id_Todo;
		}
	
	
		public void setId_Todo(Long id_Todo) {
			this.id_Todo = id_Todo;
		}
	
	
		public Long getId_Category() {
			return id_Category;
		}
	
	
		public void setId_Category(Long id_Category) {
			this.id_Category = id_Category;
		}
	}
    
    // Relations m:m tags
	public ArrayList<Long> getTags() {
		return tags;
	}

	public void setTags(ArrayList<Long> tags) {
		this.tags = tags;
	}
	
	
	public static class Todo_tags implements RowMapper<Todo_tags>{
		
		private Long _id;
		
		// Relations
	
		private Long id_Todo;
		private Long id_Tag;
				
		@Override
		public Todo_tags mapRow(ResultSet rs, int rowNum) throws SQLException {
			
			Todo_tags obj = new Todo_tags();
			try {
				obj.set_id(rs.getLong("id"));
				obj.setId_Todo(rs.getLong("id_Todo"));
				obj.setId_Tag(rs.getLong("id_Tag"));
			}
			catch(Exception e) {
				e.printStackTrace();
			}
			return obj;
		}
		public Long get_id() {
			return _id;
		}
	
		public void set_id(Long _id) {
			this._id = _id;
		}
	
		public Long getId_Todo() {
			return id_Todo;
		}
	
	
		public void setId_Todo(Long id_Todo) {
			this.id_Todo = id_Todo;
		}
	
	
		public Long getId_Tag() {
			return id_Tag;
		}
	
	
		public void setId_Tag(Long id_Tag) {
			this.id_Tag = id_Tag;
		}
	}
    
}